### ISSUE TITLE
how i build use this i got errors in all modes in sln

### ISSUE THREAD

**Issue by Project-Z1K** [raax7/OG-Fortnite-Cheat#1]

**Comment by plooshi** [comment]
imagine pasting

**Comment by blurryfn** [comment]
z1k is a skid

**Comment by Project-Z1K** [comment]
LMAO is just to play

**Comment by Project-Z1K** [comment]
z1k is ded and delete 1 year ago xd

**Comment by plooshi** [comment]
yappity you literally put my code for bots in your github i dont wanna fucking hear it

**Comment by itztiva** [comment]
z1k is a skid fr

**Comment by Project-Z1K** [comment]
bro dont stop cry

**Comment by itztiva** [comment]
???

**Comment by raax7** [comment]
Which build mode are you using? RELEASE_ENGINE? RELEASE_IMGUI? If you are using RELEASE_IMGUI, try downloading the DirectX SDK.

**Comment by Project-Z1K** [comment]
I test all modes i got 33 39 40 errors and i alr download the sdk

**Comment by Project-Z1K** [comment]
i test all building modes idk allways i got erroes and i just want to play using it i dont have discord server i cant skkid it

**Comment by raax7** [comment]
Have you removed the `static_asserts`s from the source?

**Comment by Project-Z1K** [comment]
no i didint mb

**Comment by raax7** [comment]
All good, if you have any more issues you can open another issue.
