### ISSUE TITLE
Menu not showing/cheat crashing maybe?

### ISSUE THREAD

**Issue by taxxed** [raax7/OG-Fortnite-Cheat#20]
Last few lines of log file after each injection are as follows
```
[2024-12-02 21:52:03] [Hooks.cpp:100] Initializing Hooks...
[2024-12-02 21:52:03] [Hooks.cpp:17] Create VFTHook called
[2024-12-02 21:52:03] [Hooks.cpp:23] Failed to set protection (1) on constructor for VFTIndex: 92
[2024-12-02 21:52:03] [Hooks.cpp:118] Hooks Initialized!
```
Either that is the end of the log and the cheat has successfully injected but menu not opening - which im not sure about because I haven't looked at the initial loading process at all, or it is crashing at hooks initialized

any insight would be great just tryna fuck around in ogfn

**Comment by taxxed** [comment]
Tried on Nova 9.41, and ezfn season 4 (haven’t tried s7 as their anti cheat doesn’t let me launch because of debugging tools even after closing everything

**Comment by raax7** [comment]
Nova and EZFN will both require custom bypasses to make the cheat undetected on there. It may be their anti-cheats interfering with the loading process. Could you try the cheat on a self hosted version of the game, such as Project Reboot?

**Comment by taxxed** [comment]
Found it does inject in s8 on a different project so likely to be anti cheats interfering on nova
Any ideas of a workaround? i'm using a self coded driver and injector with security against injections but havent implemented any into your source and am not sure where to start if the injection process is being interfered with

**Comment by raax7** [comment]
Most OGFN anti-cheats don't really focus on conventional detection methods, especially Nova. They usually go for the easier route of detecting interactions with Unreal-Engine, so it's a bit difficult to know where to start without reversing the anti-cheat. I'm going to close this issue now, hopefully you are able to reverse Nova or whatever project you want to use this cheat on, have a great day!
