### ISSUE TITLE
Doesnt work on chapter 2 season 6 and above

### ISSUE THREAD

**Issue by nito9999** [raax7/OG-Fortnite-Cheat#4]
When injecting, it says
![image](https://github.com/raax7/OG-Fortnite-Cheat/assets/120246447/c4681216-e396-43c2-8fe7-e8209bfc3147)

**Comment by raax7** [comment]
Can you dump the FortniteClient-Win64-Shipping.exe with Scylla and send it to me?

**Comment by nito9999** [comment]
> Can you dump the FortniteClient-Win64-Shipping.exe with Scylla and send it to me?
Whats Scylla and wheres the download for it

**Comment by raax7** [comment]
Here is the download: https://github.com/NtQuery/Scylla/releases/download/v0.9.8/Scylla_v0.9.8.rar

To dump, extract the RAR file, open Fortnite and then:
1. Open Scylla_x64.exe.
2. In the top, click the long bar and scroll through until you find "FortniteClient-Win64-Shipping.exe".
3. Once you've found it, click it to select it.
4. Press dump in the bottom right, then select where you want the file to be.
5. After that, use Google Driver or something similar to upload the file you saved.
6. Then send me the link and I will update the cheat to fix the crash.

**Comment by D1aMonDNL** [comment]
Not OP but im working on it @raax7

**Comment by D1aMonDNL** [comment]
Error: Cannot dump image.

**Comment by raax7** [comment]
Could you send a screenshot of the error? And could you walk me through how you are dumping it?

**Comment by nito9999** [comment]
I'm gonna try dumping now.

**Comment by nito9999** [comment]
https://gofile.io/d/9aGCms

**Comment by raax7** [comment]
Thank you, I will update the cheat in the next hour or so to support your new version. I will close this issue once I have updated it.

**Comment by raax7** [comment]
Just to confirm, this build is Chapter 2 Season 6 correct?

**Comment by raax7** [comment]
I've pushed a fix for this. Re-download the source code and it should work. If it still doesn't work, please re-open the issue and let me know.

**Comment by nito9999** [comment]
> Just to confirm, this build is Chapter 2 Season 6 correct?

chapter 2 season 6 to chapter 3
