### ISSUE TITLE
What injector do I use in EZFN?

### ISSUE THREAD

**Issue by ottov4** [raax7/OG-Fortnite-Cheat#6]
in EZFN with the injector that I have it won't let me inject it and I want to know which one you use

**Comment by raax7** [comment]
You can just find any Kernel-Mode injector from GitHub or Unkowncheats and compile with the settings required in Globals.h and it will work.

**Comment by nito9999** [comment]
> You can just find any Kernel-Mode injector from GitHub or Unkowncheats and compile with the settings required in Globals.h and it will work.

Can you send the injector
