### ISSUE TITLE
Im trying to Compile but It doesn't make it complete, I need to use visual studio and I can't get anything

### ISSUE THREAD

**Issue by killpepe** [raax7/OG-Fortnite-Cheat#8]
Im trying to Compile but It doesn't make it complete, I need to use visual studio and I can't get anything

**Comment by raax7** [comment]
Please go to Globals.h and delete the line with the `static_assert` like the error states. Static assertions are assertions made at compile time, I just have an assertion that will always fail at places where people need to check everything is setup correctly for them. It is not a real error, just a reminder to check the settings before you use it.
